environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install wheel pylint opencv-python numpy pytest-cov pillow"

build: off

test_script:
  - "%PYTHON%\\python.exe tst_colorscope.py"
