os: linux
dist: trusty
sudo: required
language: python

python:
  - "3.5"

addons:
  apt:
    sources:
      - sourceline: 'ppa:mc3man/trusty-media'
    packages:
      - ffmpeg

install:
  - pip install -r requirements.txt -r tst_requirements.txt

script:
  - pylint colorscope.py ip/*
  - pytest --cov-report term --cov-branch --cov=ip tst_colorscope.py


after_success:
  - coveralls
