os: linux
dist: trusty
sudo: required
language: python

python:
  - "3.5"

addons:
  apt:
    sources:
      - sourceline: 'ppa:mc3man/trusty-media'
    packages:
      - ffmpeg

install:
  - pip install pylint opencv-python xvfbwrapper pytest-cov coveralls PyUserInput pillow

script:
  - pylint colorscope.py
  - pytest --cov colorscope tst_colorscope.py

after_success:
  - coveralls
